### ISSUE TITLE
FreeBsd Install/runtime?

### ISSUE THREAD

**Issue by rhs-github** [renn0xtek9/BookMarkWidgets#2]
https://gist.github.com/rhs-github/09f95df309275dc5c9d804bdefa3835a
I'm following this repo now so if you post to your own repo I believe a notification will automajically appear.

**Comment by renn0xtek9** [comment]
Hey , thanks a lot for you info. 
Regarding FreeBSD:
Indeed I have 0 experience with FreeBSD, thus I have not tested it at all. Sorry. I should probably make a virtual machine of FreeBsd to test it in the future. If you happen to know which path I should put in the CMakeLists.txt that would be ideal. Otherwise I will try to find out. 
Regarding shortcuts to open folders:
For me it works. For example if I put a new Bookmark to "/home/max/Downloads" and then click on it, dolphins open and displays "/home/max/Downloads/" . Same thing if I test with "remote:/".  Is not not working for you ? Can it be that you do not have "xdg-open" installed on your system. 
Regarding "alter mime-types," : 
I don't remember everything what KDE4 was able to do. (But I remember it was able to do more than my plasmoid though...). I don't understand what you mean with this exactly. Could you develop ?
Regarding OpenDesktop:
I don't know I will look at, but I did not remember blocking anything on my profile on my side, so I suspect the problem does not come from me..

Don't hesitate If you have some feature wishes. Some might not necessarily be hard to implement ;)
Right now my next target is to implement "flat search". And then I will try to make the bookmark model editable. (This will take long time) But I could squeeze some more things inbetween;)

**Comment by rhs-github** [comment]
[Uploading CMakeLists.txt…]()
#query_qmake(QT_INSTALL_PLUGINS QT_PLUGINS_DIR)
#query_qmake(QT_INSTALL_IMPORTS QT_IMPORTS_DIR)#
#set(QT_IMPORTS_DIR /usr/lib/x86_64-linux-gnu/qt5/qml/)		#TODO this should be set in platform independant#
**set(QT_IMPORTS_DIR /usr/local/lib/qt5/qml/)<<<<<<<(note below)>>>>>>>>**
message(STATUS "libbookmarkmodule:  QT_IMPORTS_DIR.------------------------------------------------\n" "${QT_IMPORTS_DIR}")
message(STATUS "libbookmarkmodule:  SRC.------------------------------------------------\n" "${SRC}")
message(STATUS "libbookmarkmodule:  SRC.------------------------------------------------\n" "${PROJECT_NAME}")
**(note)**
QTDIR=/usr/local/lib/qt5/bin:/usr/local/lib/qt5 <<<<<this is in my environment  #or$ env>>>>. File /usr/local/etc/xdg/qtchooser/qt5.conf really dictates where and what version of QT your environment is using as DEFAULT in FreeBSD.
I dont know if the link will work. I have flash disabled and believe thats why these links do not appear for me? I still have my live version of all my work on kde4 and can easily boot into that environment to explore what and how it all worked there. "DD" is my best friend and I dont leave home without it.

If i activate (click) on a shortcut to a folder location in the bookmark widget I can see dolphin activating in the task bar but then the process quietly dies. Dont know why? Help!

**Comment by rhs-github** [comment]
Previous change to QT directory in CMakelists.txt did completely resolve all problems for this widget, for installation/use in FreeBSD-11.2. My problem with 'dolphin' silently failing when attempting a location was due to old icons somehow having priority over new desktop icons. Since kdesu worked in kde4 I had some desktop 'root' icons. Search and destroy all .desktop icons that attempt to open any application as another user is my advice when setting up kde5 on FreeBSD. Please also note that this widget will not show up in widgets using KDE native methods but rather you have to clone repo and patch manually, and install locally for it to work at present.
The other problem with mime-types was not a problem, just a brain fart cause I really meant 'file associations' and again some cruft from previous kde4 somehow messed them up.
 Thanks for the best time saving, get er done, widget of them all.

**Comment by renn0xtek9** [comment]
Glad to here it works! Stay tune, I have started to implement the modification of the bookmark directly from the plasmiid itself. It will take some time though
